"""add orders and conversations

Hand-corrected from autogenerate, same two defects as 0002: an unimported
`Text()` inside the JSONB variant (NameError on Postgres) and a SQLite-only
`(CURRENT_TIMESTAMP)` default.

Revision ID: 0003_orders_conversations
Revises: 0002_products
Create Date: 2026-08-29 23:42:28.682037
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0003_orders_conversations"
down_revision: str | None = "0002_products"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_intent', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'CREATED', 'AWAITING_PAYMENT', 'PAID', 'FAILED', 'CANCELLED', 'BLOCKED', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('receipt', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='ck_orders_amount_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index('ix_orders_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status_created')
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_orders_conversation_id'))

    op.drop_table('orders')
    op.drop_table('conversations')
    # ### end Alembic commands ###
