"""add audit logs

Hand-corrected from autogenerate for the same two defects as 0002 and 0003:
an unimported `Text()` inside the JSONB variant, and a SQLite-only
`(CURRENT_TIMESTAMP)` timestamp default.

Revision ID: 0004_audit_logs
Revises: 0003_orders_conversations
Create Date: 2026-08-30 00:11:21.840525
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0004_audit_logs"
down_revision: str | None = "0003_orders_conversations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.Enum('CREATE_ORDER', 'VERIFY_PAYMENT', name='auditaction', native_enum=False, length=32), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'REQUIRE_APPROVAL', 'BLOCK', name='auditdecision', native_enum=False, length=32), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'AWAITING_APPROVAL', 'SUCCEEDED', 'FAILED', 'BLOCKED', 'DECLINED', 'EXPIRED', name='auditoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_desc', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_decision_outcome', ['decision', 'outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_outcome'), ['outcome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_outcome'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_order_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_decision'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_agent_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_decision_outcome')
        batch_op.drop_index('ix_audit_created_desc')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
