"""add agent grants

Hand-corrected from autogenerate for the same two defects as every prior
revision: an unimported `Text()` inside the JSONB variant, and a SQLite-only
`(CURRENT_TIMESTAMP)` timestamp default.

Revision ID: 0005_agent_grants
Revises: 0004_audit_logs
Create Date: 2026-09-02 11:13:06.427015
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0005_agent_grants"
down_revision: str | None = "0004_audit_logs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('spend_cap_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='grantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=64), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('spend_cap_minor > 0', name='ck_grants_cap_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_grants_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_grants_status'), ['status'], unique=False)
        batch_op.create_index('ix_grants_buyer_status', ['buyer_id', 'status'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grant_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_grant_id'), ['grant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_grant_id'))
        batch_op.drop_column('grant_id')

    with op.batch_alter_table('agent_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_grants_buyer_status')
        batch_op.drop_index(batch_op.f('ix_agent_grants_status'))
        batch_op.drop_index(batch_op.f('ix_agent_grants_buyer_id'))

    op.drop_table('agent_grants')
    # ### end Alembic commands ###
